POST http://localhost:3000/api/video
Content-Type: application/json
Authorization: Bearer ALWU2cutofel9bli2/kE3KNI8xJSfbwq6bnq8ZdtBg94nKskpGr/EPH4rDnZuicMyurXTuVy/CwrN6mekROsh3aJUmbXM25FfqzUj04wWC7xfHztuQCXbaXVFF1VMUNs2Jezeb8/Qq3X3Q+oDdDboAHN/0710IIJe/GY9qf4bvsU4ZkSEr4gLTSam4VCH+5fUUuoKCqj249Z+XLLpsG1VbJ6FU2xnlDakBQmZr2WJZNmVQD3X2gz6q2RO+kWGy9YEtJsdV/X4d/r+wUbCLz7xCTV8iXjX1i9i4G1FPShbfAA0WAnXtoFiX050a5rc/WedgSIYAI440Pt3tflX0W0tloLnSsPVp3i57+Oj0ZljjVBNqNeg8Rha+/b7lf9BvgOt55gBsxCfXutQwB1y7iqmGbEKyGWi8oXTr2JaJSYdCasT2VNHUX4U+9/5WHXKWMEfwLKpHxDjVo9E45+SJYaYgs4dHlbEkYSQA==

{
    "title": "Video",
    "description": "Video description"
}
