import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Videlo - The video platform you always wanted.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button className="p-2 rounded-md bg-blue-500 text-white font-black m-2">
        <Link href="/login">Login Page</Link>
      </button>
    </div>
  );
}
