import { useUser, withPageAuthRequired } from "@auth0/nextjs-auth0";
import Head from "next/head";
import IconButton from "../components/IconButton";

import { useEffect, useState } from "react";
import {
  BellIcon,
  CameraIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ClockIcon,
  CogIcon,
  HomeIcon,
  MicrophoneIcon,
  MoonIcon,
  PencilAltIcon,
  PhotographIcon,
  PlayIcon,
  QuestionMarkCircleIcon,
  RssIcon,
  SearchIcon,
  UserAddIcon,
  UserIcon,
  VideoCameraIcon,
  XIcon,
} from "@heroicons/react/outline";
import InputField from "../components/InputField";
import MenuLayout from "../components/layouts/MenuLayout";
import MenuOption from "../components/MenuOption";
import Link from "next/link";
import VideoCard from "../components/VideoCard";
import SidebarOption from "../components/SidebarOption";

export default withPageAuthRequired(function Home() {
  const [search, setSearch] = useState(false);
  const [notification, setNotification] = useState(false);
  const [profile, setProfile] = useState(false);
  const [videoOptions, setVideoOptions] = useState(false);
  const [micMenu, setMicMenu] = useState(false);
  const [sidebar, setSidebar] = useState(false);

  const { user, error, isLoading } = useUser();

  const [searchField, setSearchField] = useState("");
  const [countryCode, setCountryCode] = useState("");
  const [inputField, setInputField] = useState("");

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(onSuccess, onError);
    }
  }, []);

  const onSuccess = (position) => {
    const { latitude, longitude } = position;
    fetch(
      `https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en`
    )
      .then((res) => res.json())
      .then((data) => setCountryCode(data.countryCode));
  };

  const onError = (error) => {
    return <h1>{error}</h1>;
  };

  const convert = () => {
    const speech = true;
    // Set window.SpeechRecognition to webkit.SpeechRecognition so it works on safari
    window.SpeechRecognition = window.webkitSpeechRecognition;
    const recognition = new SpeechRecognition();
    // convert voice to text
    recognition.interimResults = true;

    recognition.addEventListener("result", (e) => {
      const translation = Array.from(e.results)
        .map((res) => res[0])
        .map((res) => res.transcript);

      setSearchField(translation);
    });
    if (speech === true) {
      recognition.start();
    }
  };

  return (
    <div className="bg-background-color h-screen fixed top-0 w-screen p-4">
      <Head>
        <title>Videlo - The video platform you always wanted.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="section z-50 sticky top-0">
        {!search ? (
          <div className="flex items-center justify-between">
            <div className="relative w-max p-2">
              <img src="/videlo.png" alt="Logo" />
              <h1 className="absolute right-1 text-xs text-gray-400 top-0">
                {countryCode}
              </h1>
            </div>
            <div className="hidden sm:flex sm:flex-[0.8] xl:flex-[0.6] 2xl:flex-[0.4]">
              <InputField
                Icon={SearchIcon}
                placeholder="Search Videlo"
                value={searchField}
                setValue={setSearchField}
                type="text"
                className="rounded-tr-none rounded-br-none"
              />
              <div
                className="p-2 bg-zinc-800 w-16 flex justify-center cursor-pointer active:bg-zinc-900 transition-all duration-200"
                onClick={() => {
                  setMicMenu(true);
                  convert();
                }}
              >
                <MicrophoneIcon className="h-6 text-white" />
              </div>

              {micMenu && (
                <MenuLayout
                  headerText="Record your voice"
                  setMenu={setMicMenu}
                  className="fixed inset-x-0 mx-auto w-[500px] top-[70px] h-[500px]"
                >
                  <div className="p-5 bg-red-500 rounded-full">
                    <MicrophoneIcon className="h-20 text-white" />
                  </div>
                </MenuLayout>
              )}
            </div>
            <div className="flex items-center space-x-2">
              <IconButton
                Icon={SearchIcon}
                onClick={() => setSearch(true)}
                className="sm:hidden"
              />
              <IconButton
                Icon={CameraIcon}
                onClick={() => setVideoOptions(!videoOptions)}
              />
              <IconButton
                Icon={BellIcon}
                onClick={() => setNotification(!notification)}
              />
              <IconButton Icon={UserIcon} onClick={() => setProfile(true)} />
            </div>
            {videoOptions && (
              <MenuLayout
                setMenu={setVideoOptions}
                className="fixed right-[116px] top-[70px] w-[240px] h-[170px]"
                headerText="Create Videos"
              >
                <MenuOption
                  Icon={VideoCameraIcon}
                  text="Upload Video"
                  className="mt-10"
                />
                <MenuOption Icon={RssIcon} text="Go Live" />
              </MenuLayout>
            )}
            {notification && (
              <MenuLayout
                setMenu={setNotification}
                className="fixed right-[68px] top-[70px] w-[290px] h-[411px]"
                headerText="Notifications"
              >
                <h1 className="text-[25px] text-white font-[700] text-center">
                  There aren't any notifications here
                </h1>
                <img
                  src="/person_in_bush.png"
                  alt="person in bush"
                  loading="lazy"
                  className="translate-x-4"
                />
              </MenuLayout>
            )}
            {profile && (
              <MenuLayout
                setMenu={setProfile}
                className="fixed right-4 top-[70px] w-[290px] h-[480px]"
                headerText="Profile"
              >
                <div className="w-full bg-[#454545] h-max rounded-md flex items-center space-x-3 mb-5">
                  <img
                    src={user.picture}
                    alt="Profile pic"
                    loading="lazy"
                    referrerPolicy="no-referrer"
                    className="h-16 rounded-tl-md rounded-bl-md"
                  />
                  <div className="overflow-x-hidden">
                    <h1 className="truncate font-bold text-white text-lg">
                      {user?.name}
                    </h1>
                    <p className="px-2 py-1 bg-[#656565] text-white rounded-sm font-bold text-xs w-max">
                      <Link href="/api/auth/logout">Sign out</Link>
                    </p>
                  </div>
                </div>
                <MenuOption Icon={PlayIcon} text="Your channel" />
                <MenuOption Icon={MoonIcon} text="Appereance: Dark" />
                <MenuOption Icon={CogIcon} text="Settings" />
                <MenuOption Icon={QuestionMarkCircleIcon} text="Help" />
                <MenuOption Icon={PencilAltIcon} text="Send feedback" />
                <MenuOption Icon={UserAddIcon} text="Add more accounts" />
              </MenuLayout>
            )}
          </div>
        ) : (
          <div className="flex items-center justify-between space-x-5">
            <InputField
              type="text"
              placeholder="Search Videlo"
              Icon={SearchIcon}
              value={inputField}
              setValue={setInputField}
            />
            <IconButton Icon={XIcon} onClick={() => setSearch(false)} />
          </div>
        )}
      </header>

      <div className="my-4 h-[88%]">
        <div
          className="section flex items-center my-3 text-white space-x-2 cursor-pointer active:bg-[#313131] transition-colors duration-300"
          onClick={() => setSidebar(true)}
        >
          <ChevronRightIcon className="h-6" />
          <h1>Open Sidebar</h1>
        </div>
        {sidebar && (
          <div className="fixed w-full h-screen top-0 left-0 z-50 text-white bg-black bg-opacity-50 transition-opacity duration-300">
            <div className="rounded-none section w-[20rem] sidebar-animation h-full relative">
              <IconButton
                Icon={ChevronLeftIcon}
                onClick={() => setSidebar(false)}
                className="absolute right-5 top-5"
              />
              <img
                src="/videlo.png"
                alt="Logo"
                loading="lazy"
                className="absolute top-32 inset-x-0 mx-auto w-28"
              />
              <div className="space-y-2 flex flex-col justify-center h-full">
                <SidebarOption Icon={HomeIcon} text="Home" />
                <SidebarOption Icon={CheckIcon} text="Subscription" />
                <SidebarOption Icon={VideoCameraIcon} text="My Videos" />
                <div className="seperator"></div>
                <SidebarOption Icon={ClockIcon} text="Watch Later" />
                <SidebarOption Icon={CheckCircleIcon} text="Liked Videos" />
                <SidebarOption Icon={PhotographIcon} text="Playlists" />
                <div className="seperator"></div>
                <div className="max-w-[20rem] mx-auto text-center">
                  <img
                    src="/videlo.png"
                    alt="logo"
                    className="object-contain w-28 mx-auto mt-5 mb-3"
                  />
                  <p className="text-xs">
                    Videlo is an online video sharing website and social media
                    platform
                  </p>
                  <p className="text-sm text-black mt-5">Videlo © 2022</p>
                </div>
              </div>
            </div>
          </div>
        )}
        <main className="section h-[98%] w-full overflow-y-auto gap-5 xl:gap-8 flex flex-wrap justify-center scrollbar">
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="Second video on Videlo wow so amazing it's amazing wow"
            channelImage="https://i.ytimg.com/vi/_MLMuvZFbIE/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDJ3KhLB2rl7p2FV2heHOwc21v1vg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/_MLMuvZFbIE/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDJ3KhLB2rl7p2FV2heHOwc21v1vg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/eIc4mqyN1Q8/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLD-oHCZyQatiNadb9RI_ZDN7nDRRQ"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/QZbJOBZqKnM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBuhL_cZh2iixpxdzYZ3m7cQpe0Cw"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/e4zT0dJnEVQ/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBrRoaY_SYiuIm2D_wDllGHmnC-gw"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/edzt82nC45k/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA0sC5BoNG5Qr4wHd1LvvMmbsUtzA"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/eYaSNZRbFsA/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCu_sYmMfv8kHY8TrWwR7zGw2oH-w"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/iomtX7cg7sE/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCYWMic5oztTFhHLd_zL79TU55hFA"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
          <VideoCard
            title="First video on Videlo"
            channelImage="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            channelName="Channel Name"
            createdAt="20 Aug 22"
            views="12M"
            thumbnail="https://i.ytimg.com/vi/2KuabuIBc9I/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLARwNmUNKt2Eizd2_QUdKs7LGu_eg"
            likes="12M"
            dislikes="1M"
          />
        </main>
      </div>
    </div>
  );
});
